
SUPPORT_USERNAME = "@dnrvv"

CATEGORY_CODE_LENGTH = 20
CATEGORY_NAME_LENGTH = 20
PRODUCT_NAME_LENGTH = 150
PRODUCT_CAPTION_LENGTH = 250

MAX_PRODUCT_IN_CART_QUANTITY = 100

KM_DELIVERY_PRICE = 3000

BOT_USERNAME = "botfatherdev_final_bot"
CHANNEL_USERNAME = "@yumyum_channel"
